# Generated by Django 5.0.4 on 2024-05-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workeruser",
            name="title",
        ),
        migrations.AddField(
            model_name="workeruser",
            name="position",
            field=models.CharField(
                choices=[
                    ("Guest", "Guest"),
                    ("Developer", "Developer"),
                    ("Project Manager", "Project Manager"),
                    ("Product Manager", "Product Manager"),
                    ("QA", "QA"),
                    ("Designer", "Designer"),
                    ("DevOps", "DevOps"),
                    ("Team Lead", "Team Lead"),
                ],
                default="Guest",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="workeruser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Engineer/Manager", "Engineer/Manager"),
                    ("Supervisor", "Supervisor"),
                ],
                default="Engineer/Manager",
                max_length=64,
            ),
        ),
    ]
