# Generated by Django 5.0.4 on 2024-05-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_workeruser_title_workeruser_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workeruser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Guest", "Guest"),
                    ("Engineer/Manager", "Engineer/Manager"),
                    ("Supervisor", "Supervisor"),
                ],
                default="Guest",
                max_length=64,
            ),
        ),
    ]
