# Generated by Django 5.0.4 on 2024-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_workeruser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workeruser",
            name="telegram",
            field=models.CharField(
                blank=True,
                help_text="Telegram username (@username)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
