# Generated by Django 5.0.4 on 2024-05-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_workeruser_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workeruser",
            options={"ordering": ["-username"]},
        ),
    ]
