# Generated by Django 5.0.4 on 2024-05-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_workeruser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workeruser",
            options={"ordering": ["username"]},
        ),
    ]
