# Generated by Django 5.0.4 on 2024-05-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_workeruser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workeruser",
            options={"ordering": ["username"], "verbose_name": "worker"},
        ),
    ]
