# Generated by Django 5.0.4 on 2024-05-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_workeruser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="workeruser",
            name="last_activity",
            field=models.DateField(blank=True, null=True),
        ),
    ]
