# Generated by Django 5.0.4 on 2024-05-08 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"], "verbose_name": "project"},
        ),
        migrations.RenameField(
            model_name="project",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="project",
            name="project_lead",
            field=models.ForeignKey(
                limit_choices_to={"role": "Supervisor"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
