# Generated by Django 5.0.4 on 2024-05-22 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_comment_author_alter_task_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created"],
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created"],
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="responsible_workers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="workers_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="project_tasks",
                to="projects.task"
            ),
        ),
    ]
